### PR TITLE
refactor: Move statesync_test canister to Rust CDK

### PR DESCRIPTION
**Pull request by dsarlis**
`dfn_core` is considered deprecated and the plan is to eventually remove it. Therefore, we need to move any canisters in the `ic` repo that still depend on it to instead use the public CDK. This PR migrates the `statesync_test` canister.

### CODE REVIEW

**Review by max-dfinity — APPROVED** [review]

**Comment by derlerd-dfinity** [comment]
Given that we ran into quite some trouble with the XNet test canister port, would it be possible to trigger all the tests that typically also run on an RC on this one?

**Comment by dsarlis** [comment]
> Given that we ran into quite some trouble with the XNet test canister port, would it be possible to trigger all the tests that typically also run on an RC on this one?

I have asked the team to let me know what I need to run. I have confirmed that both `rejoin_test_large_state` and `state_sync_malicious_chunk_test` are successful on the latest commit. If there are more I need to run, let me know.

**Comment by derlerd-dfinity** [comment]
> I have asked the team to let me know what I need to run. I have confirmed that both `rejoin_test_large_state` and `state_sync_malicious_chunk_test` are successful on the latest commit. If there are more I need to run, let me know.

Please trigger the pipelines that usually run on an RC. My concern is that -- similar to last time -- running selective tests will make us miss some subtle connections.

**Review by ShuoWangNSL — APPROVED** [review]
Thanks. The refactoring looks good to me.

**Comment by dsarlis** [comment]
[Release testing pipeline is green](https://github.com/dfinity/ic/actions/runs/12257480440) on latest commit.

cc @derlerd-dfinity

**Comment by derlerd-dfinity** [comment]
> [Release testing pipeline is green](https://github.com/dfinity/ic/actions/runs/12257480440) on latest commit.
> 
> cc @derlerd-dfinity

Thanks a lot @dsarlis for running these tests! Given that Shuo has already approved the code changes feel free to go ahead with merging right away.

**Pull request merged**
