### PR TITLE
fix: Fix bug in StreamsTesting fixture

### PR DESCRIPTION
**Pull request by alin-at-dfinity**
Previously hidden by `queues::MemoryUsageStats`' custom `PartialEq` implementation (that ignored `transient_stream_responses_size_bytes`); and not triggered by the original `StreamHandler` tests (that cloned the state before any streams were populated); this suddenly started causing test failures with the combination of new `StreamHandler` test fixtures and `queues::QueueStats` that include `transient_stream_responses_size_bytes` in equality comparisons.

The issue is that `responses_size_bytes` is only supposed to have its zero values pruned after they have been applied to the corresponding canisters' `transient_stream_responses_size_bytes`. Simply wiping them clean when replacing the streams left canisters with outdated non-zero `transient_stream_responses_size_bytes` fields.

Instead, when replacing the streams, retain all `responses_size_bytes` keys with a default of zero. This ensures that the respective canisters' stats will be correctly reset to zero where necessary.

### CODE REVIEW

**Review by berestovskyy — APPROVED** [review]
Do some existing tests fail from time to time, or should we consider adding a new test?

**Comment by stiegerc** [comment]
So when where does it set to 0 and then prunes entries? [Here](https://sourcegraph.com/github.com/dfinity/ic@435bdcc9f167012452c470f6b6b7f5e2f928c7ee/-/blob/rs/execution_environment/src/scheduler.rs?L1174)?

**Comment by alin-at-dfinity** [comment]
> So where does it set to 0 and then prunes entries? [Here](https://sourcegraph.com/github.com/dfinity/ic@435bdcc9f167012452c470f6b6b7f5e2f928c7ee/-/blob/rs/replicated_state/src/replicated_state.rs?L834:51-834:82)?

Precisely. And that gets called from `put_streams()`.

**Review by stiegerc — APPROVED** [review]
LGTM. Thanks for the fix.

**Pull request merged**
