### PR TITLE
chore(IDX): update slack alerts

### PR DESCRIPTION
**Pull request by cgundy**
Request from Crypto team to move alerts for `Schedule Rust Benchmarks` and `Bazel System Test Benchmarks` to dedicated slack channel.

### CODE REVIEW

**Review by altkdf — APPROVED** [review]

**Review by basvandijk — COMMENTED** [review]
I'm a bit confused because the crypto team doesn't own any [system_test_benchmark](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/dfinity/ic%24+%22system_test_benchmark%22%2C&patternType=keyword&sm=0). Why would they need to receive notifications for them?

I also wonder if we shouldn't use Superset alerts for this such that we can send alerts for individual bazel tests.

**Review by basvandijk — APPROVED** [review]
OTOH if they asked for this I also don't have an issue with that.

**Comment by altkdf** [comment]
> I'm a bit confused because the crypto team doesn't own any [system_test_benchmark](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/dfinity/ic%24+%22system_test_benchmark%22%2C&patternType=keyword&sm=0). Why would they need to receive notifications for them?
> 
> I also wonder if we shouldn't use Superset alerts for this such that we can send alerts for individual bazel tests.

I guess because we are the most interested in those tests right now :) We could also talk with consensus and ask if they want to take care of the alerts. But it should be fine if crypto gets the alerts for some time IMO, at least better than not noticing that something is broken.

**Comment by basvandijk** [comment]
Yes that sounds good, let's merge.

**Comment by altkdf** [comment]
And re alerts for individual bazel test, I agree that it would be better that crypto gets alerts only for `Bazel Run Rust Benchmarks (//rs/crypto/...)` and `Bazel Run Rust Benchmarks (//rs/certification/...)`, but I doubt that we will see much noise caused by the other targets. So should be good enough for now as well.

**Pull request merged**
