### PR TITLE
replace broken link

### PR DESCRIPTION
**Pull request by abebeos**

### CODE REVIEW

**Comment by abebeos** [comment]
@dsarlis , @nikola-milosa , @bitdivine 
@smallstepman , @sasa-tomic , @Dfinity-Bjoern 

what is this nonsense "error" message? At least include a pointer "how to fix our broken links"

A new internet with such flawed processes?

**Comment by sasa-tomic** [comment]
Apologies for this message and for the bot @abebeos. The IDX team is working on providing a way for allowing external contributions. So hopefully the "nonsense error message" will soon be a thing of past.

fyi @levshaATdfinity 

OTOH, your change makes sense and I'll create another internal MR to change the repo. This public repo mirror does not have the CI system set up and thus can't accept external contributions. This is the core issue, actually.

**Comment by abebeos** [comment]
> The IDX team is working on providing a way for allowing external contributions.

It is simple: follow standard-procedure.

**Comment by abebeos** [comment]
(talking myself to death just to fix a broken link...)

**Comment by sasa-tomic** [comment]
> It is simple: follow standard-procedure.
I wish it was that easy.

BTW, I already created an MR with the change in the internal repo, so the change should appear in the public repo soon. Thanks for your contribution!

**Comment by sasa-tomic** [comment]
There we are: https://github.com/dfinity/ic/commit/c4402922e122ebd21075c6561a44c002f1cc4b6d

**Pull request closed without merging**
