### PR TITLE
fix: disable node exporter netlink metrics collection

### PR DESCRIPTION
**Pull request by tthebst**
Recently the node exporter was upgraded from 1.2 to 1.8. With this change the `arp` and `netdev` collector switched to using `netlink` to collect metrics. The current selinux policy on the guestos does not allow the node exporter process to open netlink socket and therfore the the `arp` and `netdev` metrics are currently missing.

This MR disables the netlink metrics scarping by switching back to scaping `/proc/net/dev` as was done by default before version 1.4.

### CODE REVIEW

**Comment by nabdullindfinity** [comment]
The netlink-related permissions in that macro are a bit too broad (e.g. all ioctl for some reason?) for a network-facing service. I don't believe we are even actively using any collectors of `node_exporter` that absolutely reqire netlink at the moment, it appears to be using `/proc/net/dev` for the `netdev` collector successfully (there is a flag `--collector.netdev.netlink` that can be used to force netlink usage)

**Comment by tthebst** [comment]
We recently upgraded node exporter from 1.2 to 1.8 and since 1.4 node exporter uses netlink by default to scrape the network metrics but you could disable it with `--no-collector.netdev.netlink` and use  `/proc/net/dev`.

I can try to remove some of the permissions.

**Comment by nabdullindfinity** [comment]
Alternatively, we could try filtering allowed `ioctl`'s further, by their codes with `allowxperms`, but for now I would say it is better to avoid exposing the netlink functionality of the kernel to `node_exporter` altogether. I understand that `node_exporter` networking-related collectors, apparently, have switched to netlink for performance reasons on high-loaded machines, but I don't believe we are close to hitting those bottlenecks in the observability stack.

**Comment by tthebst** [comment]
I added the cli options to disable netlink and use the old scarping method. Now no adjustment to selinux policy is needed.

**Review by nabdullindfinity — APPROVED** [review]
Thank you!

**Pull request merged**
