### PR TITLE
fix(IDX): update dependency tests for ic-private

### PR DESCRIPTION
**Pull request by cgundy**
This updates all the direct references to the "ic" repo to use the repo-name instead.

### CODE REVIEW

**Comment by venkkatesh-sekar** [comment]
@cgundy I don't think this change is necessary right now

1. repository_name is the primary key in JIRA for findings and if there are two different keys for it, it's going to block hotfix releases as there will be a new finding flagged. 
2. Right now, all tests must works on ic-private. If the failures become more frequent, then we can revisit this change again. WDYT?

**Comment by cgundy** [comment]
Hi, these are the failures: https://github.com/dfinity/ic-private/actions/runs/11107291696/job/30857546654 - it looked like it was only one test. Do you know what needs to be fixed?

**Comment by venkkatesh-sekar** [comment]
In #1746 all tests should have been fixed. Looks like I missed a single file when applying the patch from `ic-private` to `ic`.

Do you want to add it in this PR and remove the other changes? 

https://github.com/dfinity/ic-private/pull/37/files

**Comment by cgundy** [comment]
Do you mind creating a new PR? We can keep this one for reference, in case it's helpful to simplify these tests later on. 

Is the URL not an issue? You just always query the public ic repo, also when running from the private one?

**Comment by venkkatesh-sekar** [comment]
> Do you mind creating a new PR? We can keep this one for reference, in case it's helpful to simplify these tests later on.

Sure

> Is the URL not an issue? You just always query the public ic repo, also when running from the private one?
Yes, for the IC repo, the URL is a no-op. It's for other external repos which we need to clone.

**Pull request closed without merging**
