### PR TITLE
chore(IDX): migrate rosetta-api-release

### PR DESCRIPTION
**Pull request by cgundy**

### CODE REVIEW

**Review by mbjorkqvist — APPROVED** [review]
With my limited knowledge of github actions and workflows this LGTM!

Clarifying questions: For cutting a Rosetta release, this workflow would be run manually from the Github UI, and the workflow would build and push the image and create a tag? And the rosetta version would need to be updated in the `BUILD.bazel` and `Cargo.toml` files before running the workflow? What happens if the version in the aforementioned files don't match what is specified in the workflow?

**Comment by NikolasHai** [comment]
> With my limited knowledge of github actions and workflows this LGTM!
> 
> Clarifying questions: For cutting a Rosetta release, this workflow would be run manually from the Github UI, and the workflow would build and push the image and create a tag? And the rosetta version would need to be updated in the `BUILD.bazel` and `Cargo.toml` files before running the workflow? What happens if the version in the aforementioned files don't match what is specified in the workflow?

We have to manually bump the rosetta versions in bazel and cargo as well as the CHANGELOG file. The rest is done dynamically. The workflow is the same which we had back when we were still working on Gitlab, so no change in functionality is expected here. It just had not been migrated yet to Github. 
If the files are not bumped (meaning cargo, bazel etc) then the workflow will only create a release for the gith hash and the date, not the tag. So we have to be careful about this, we want all three to be released at the same time usually.

**Comment by cgundy** [comment]
If you would prefer, we could add another check to make sure the version specified in the input matches the bazel version file. That would prevent any human error.

**Comment by NikolasHai** [comment]
> If you would prefer, we could add another check to make sure the version specified in the input matches the bazel version file. That would prevent any human error.

That would be great

**Review by StephanusFischer — APPROVED** [review]

**Review by manudrijvers — APPROVED** [review]
codeowners lgtm

**Review by NikolasHai — APPROVED** [review]

**Pull request merged**
