### PR TITLE
chore(ICP_ledger): FI-1475: Add canister ID of 3rd ICP ledger archive

### PR DESCRIPTION
**Pull request by mbjorkqvist**
Add the canister ID of the 3rd ICP ledger archive.

### CODE REVIEW

**Review by maciejdfinity — APPROVED** [review]
As discussed offline we could also add it to https://github.com/dfinity/ic/blob/679d221aef6764f01bac26983dbc5d44410e501e/rs/nns/constants/src/lib.rs#L178

**Comment by mbjorkqvist** [comment]
> As discussed offline we could also add it to
> 
> https://github.com/dfinity/ic/blob/679d221aef6764f01bac26983dbc5d44410e501e/rs/nns/constants/src/lib.rs#L178

Done, thanks for catching this!

**Review by max-dfinity — APPROVED** [review]

**Comment by max-dfinity** [comment]
Thanks @mbjorkqvist - I wonder if upgrading the ledger archive to use more space (or stable memory) would be worthwhile?  It seems like only yesterday when the second archive spawned... things are moving quick!

**Comment by mbjorkqvist** [comment]
> Thanks @mbjorkqvist - I wonder if upgrading the ledger archive to use more space (or stable memory) would be worthwhile? It seems like only yesterday when the second archive spawned... things are moving quick!

Yes, addressing this is definitely on our roadmap!

**Pull request merged**
