### PR TITLE
chore(ecdsa): Replace nested if-match-if's with a single match

### PR DESCRIPTION
**Pull request by kpop-dfinity**
Replaced 
```
if {
  match  {
    None => if {} else {}
    Some => if {} else {} 
  }
} else {
  match  {
    None => if {} else {}
    Some => if {} else {} 
  }
},
```
which was hardly readable for me, with one big `match`

### CODE REVIEW

**Review by schneiderstefan — APPROVED** [review]

**Comment by dfinity-berestovskyy** [comment]
I'm not sure why Maksym's commits are included in this PR?

**Comment by kpop-dfinity** [comment]
> I'm not sure why Maksym's commits are included in this PR?

I think it's because the `mirroring` branch is behind the `master` branch and I merged the `master` branch into my branch shortly before sending out this PR. At least this is my guess. I posted a comment on #idx channel here: https://dfinity.slack.com/archives/CL7Q2RXUM/p1717511859910749

**Comment by dfinity-berestovskyy** [comment]
Ok, I'm assuming the `mirroring` will catch up and you won't need our approvals...

**Comment by kpop-dfinity** [comment]
> Ok, I'm assuming the `mirroring` will catch up and you won't need our approvals...

That's my hope, but the lag between `mirroring` and `master` seems to be increasing

**Review by dfinity-berestovskyy — APPROVED** [review]

**Comment by kpop-dfinity** [comment]
I was told by the IDX team to create branches from `mirroring` branch instead of `master` branch. 
I'll close this PR and create a new one.
Sorry for the notifications :)

**Pull request closed without merging**
